# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool: Default

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
      displayName: 'Install Node.js'

    - script: npm install
      displayName: 'Install dependencies'

    - script: npm run build
      displayName: 'Build application'

    - task: CopyFiles@2   # Add a task to copy the build artifact
      inputs:
        SourceFolder: /home/ubuntu/myagent/_work/2/s
        Contents: '**'  # Copy all files and subdirectories
        TargetFolder: /home/ubuntu/myagent/_work/2/a
      displayName: 'Copy build artifact to artifact directory'

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: /home/ubuntu/myagent/_work/2/a
        artifactName: 'node-app-artifact'
        publishLocation: 'Pipeline'


- stage: Test
  jobs:
  - job: TestJob
    steps:
    - script: npm install
      displayName: 'Install dependencies for testing'

    - script: npm test
      displayName: 'Run unit tests'

